# Generated by Django 5.0.3 on 2025-07-10 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AhonUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonDetectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SAR_Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_started', models.DateTimeField()),
                ('date_time_ended', models.DateTimeField(blank=True, null=True)),
                ('sar_team_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stream_api.ahonuser')),
                ('sar_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stream_api.sar_team')),
            ],
        ),
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_live', models.BooleanField(default=False)),
                ('snapshot', models.ImageField(blank=True, null=True, upload_to='snapshots/')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stream_api.mission')),
            ],
        ),
        migrations.CreateModel(
            name='Victim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.CharField(max_length=100, unique=True)),
                ('person_recognition_confidence', models.FloatField()),
                ('bounding_box', models.JSONField()),
                ('coco_keypoints', models.JSONField()),
                ('movement_category', models.CharField(blank=True, default='unknown', max_length=50, null=True)),
                ('risk_category', models.CharField(blank=True, default='unknown', max_length=50, null=True)),
                ('is_found', models.BooleanField(default=False)),
                ('estimated_longitude', models.FloatField(blank=True, default=0.0, null=True)),
                ('estimated_latitude', models.FloatField(blank=True, default=0.0, null=True)),
                ('detection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stream_api.detection')),
            ],
        ),
        migrations.CreateModel(
            name='PostureClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posture', models.CharField(default='unknown', max_length=50)),
                ('confidence', models.FloatField(default=0.0)),
                ('victim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stream_api.victim')),
            ],
        ),
        migrations.CreateModel(
            name='SAR_Team_Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('sar_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stream_api.sar_team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stream_api.ahonuser')),
            ],
            options={
                'unique_together': {('user', 'sar_team')},
            },
        ),
    ]
