# Generated by Django 5.0.3 on 2025-07-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='victim',
            name='risk_category',
        ),
        migrations.AddField(
            model_name='victim',
            name='condition',
            field=models.CharField(blank=True, default='Unknown', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='victim',
            name='movement_category',
            field=models.CharField(blank=True, default='Mobile', max_length=50, null=True),
        ),
    ]
