# Generated by Django 5.0.3 on 2025-07-10 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stream_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SAR_Team',
            new_name='SARTeam',
        ),
        migrations.RenameModel(
            old_name='SAR_Team_Member',
            new_name='SARTeamMember',
        ),
    ]
