# Generated by Django 5.0.3 on 2025-07-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream_api', '0002_remove_victim_risk_category_victim_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persondetectionmodel',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
