# Generated by Django 5.0.3 on 2025-07-11 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream_api', '0002_rename_sar_team_sarteam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='person_detection_model',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='stream_api.persondetectionmodel'),
        ),
    ]
