# Generated by Django 5.0.3 on 2025-07-12 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream_api', '0003_detection_person_detection_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='snapshot',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
